In [1]:
import numpy as np

In [3]:
arr=np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[2:6]

array([2, 3, 4, 5])

In [9]:
arr[8]

8

In [10]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
arr[8:]

array([ 8,  9, 10])

In [12]:
#broadcast

arr[0:5]=100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr=np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_arr=arr[0:6]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:]=99

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy=arr.copy()

In [24]:
arr_copy[:]=100

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [28]:
#if you are grabing a slice of the array , then it is only refrenced not getting copy, but to copy use copy function

In [29]:
mat=np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8]])

In [30]:
mat

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [33]:
mat[1,2]

4

In [34]:
mat[1]

array([2, 3, 4, 5, 6])

In [36]:
#also
mat[1][2]   #is same as mat[1,2]

4

In [37]:
arr=np.arange(1,11)

In [38]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
bool_arr=arr%2!=0

In [43]:
arr[bool_arr]   #only return element where bool_arr is true

array([1, 3, 5, 7, 9])

In [44]:
#also
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [45]:
new_arr=np.arange(50)

In [48]:
arr=new_arr.reshape(5,10)

In [52]:
arr2=arr[1,3:7]

In [53]:
arr2

array([13, 14, 15, 16])

In [54]:
arr2[arr2%2==0]

array([14, 16])